### PR TITLE
just to make it work

### PR DESCRIPTION
**Pull request by nonpro**
Hello!
I make two little changes.

### CODE REVIEW

**Comment by BELGRADE-OUTLAW** [comment]
Thanks for the PR.

**Comment by jaan143** [comment]
@BELGRADE-OUTLAW  will you please update the script ? because in scribd app there not showing directory which you instructed

**Comment by LadyHaywood** [comment]
Sorry, I've no idea where else to ask this but does this still work and does it work with books? I don't have a document_cashe file it's looking for and I'm think it's because I've downloaded books?

**Comment by jaan143** [comment]
@nonpro  Dear is it working fine in your side ?
how can find shared_prefs and key.xml file
please help me

**Pull request merged**
